version: "3"
services:
    app:
        image: tmp2:latest
        container_name: app2
        restart: unless-stopped
        build:
            # build the image from Dockerfile
            context: .
        volumes:
            - .:/code
        command: lapis server
        ports:
            - "8080:8080"
